config/routes.rb
Lab2::Application.routes.draw do
  # Latest Entry
  root :to => "pages#latest"
  # All Entries
  get "/all", :to => "pages#index", :as => :all
  # Search for name
  get '/search/:name/name', :to => "pages#name", :as => :search_name
  get '/search/:desc/desc', :to => "pages#desc", :as => :search_desc
  get '/search/:img/img', :to => "pages#img", :as => :search_img
  # # Search for desc
  # match '/search/:desc/desc',
  #             :controller => :pages,
  #             :action => "desc"
  # # Search for image
  # match '/search/:img/img',
  #             :controller => :pages,
  #             :action => "img"

  get "/about", :to => "pages#about", :as => :about
  get "/gallery", :to => "pages#gallery", :as => :gallery
  get "/latest", :to => "pages#latest", :as => :latest
end

app/models/item.rb
class Item < ActiveRecord::Base
	#attr_accessible :name, :desc, :img

	def self.search(search)
  if search
    find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
    find(:all)
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@items = Item.all
	end

	def latest
		@item = Item.last
	end

	def name
		entry = Item.where("name like ?", "%#{params[:name]}%")
      @entries=[]
      
      for x in entry do
        @entries<<Item.find_by_name(x.name) 
      end
	end

	def desc
		entry = Item.where("desc like ?", "%#{params[:desc]}%")
      @entries=[]
      
      for x in entry do
        @entries<<Item.find_by_desc(x.desc) 
      end
	end

	def img
		entry = Item.where("img like ?", "%#{params[:img]}%")
      @entries=[]
      
      for x in entry do
        @entries<<Item.find_by_img(x.img) 
      end
	end

	def about
	
	end

	def gallery
		
	end
end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<title>Lab 2 ~(-_-~)</title>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Lab 2: Routes, Controllers, Views", root_path %></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Home - Latest", root_path %></li>
      <li class="divider"></li>
      <li><%= link_to "All Items", all_path %></li>
      <li class="divider"></li>
      <li><%= link_to "About", about_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Gallery", gallery_path %></li>
    </ul>
  </section>
</nav>

<div class="row">
  <div class="small-9 columns" style="padding-right:50px"><%= yield %></div>
  <div class="small-3 columns">
    <h2 class="subheader">This is Lab 2</h2>
    <b>Submitted by:</b><br><br>
    Giselle Lingcon - 4 BS MIS<br><br>
    Sai Osano - 4 BS MIS<br><br>
    Rimina Patolot - 4 BS MIS<br><br>
    Ryan Santos - BS MIS<br><br><br>

    <b>To search:</b><br><br>
    /search/:name/name<br>
    <i>For the name of the item</i><br><br>
    /search/:desc/desc<br>
    <i>For the description of the item</i><br><br>
    /search/:img/img<br>
    <i>For the image filename of the item</i><br>
  </div>
</div>

<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%=stylesheet_link_tag "jquery.orbit.css"%>
    <%= javascript_include_tag "jquery.orbit"%>

    <%= csrf_meta_tags %>
  </head><!-- 

</html>

app/views/pages/about.html.erb
<title>About</title>
<h1> About Us </h1>

<div id="about">
	<center>
		<h3>Lab 2: Routes, Controllers, Views</h3>
		<h4>Made by:</h4>
		<ul class="small-block-grid-4">
		 <li><%= image_tag "Gis.jpg" %><br>Giselle Lingcon<br>4 BS MIS</li>
		 <li><%= image_tag "Sai.jpg" %><br>Sai Osano<br>4 BS MIS</li>
		 <li><%= image_tag "Mina.jpg" %><br>Rimina Patolot<br>4 BS MIS</li>
		 <li><%= image_tag "Ryan.jpg" %><br>Ryan Santos<br>4 BS MIS</li>
		</ul>
	</center>
</div>

app/views/pages/desc.html.erb
<h1>Search Results</h1>
<% if @entries.count > 1 %>
	<p>You have <%= @entries.count %> matches with the description <i>"<%= params[:desc] %>"</i>:</b><p>
<% elsif @entries.count == 1 %>
	<p>You have <%= @entries.count %> match with the description <i>"<%= params[:desc] %>"</i>:</b><p>
<% else %>
	<p>Your search returned 0 results. Try another description!</p>
<% end %>
<center>
<ul class="small-block-grid-2">
<% @entries.each do |x| %>
<li>
	<b><%= x.name%></b><br>
	<%= image_tag x.img, :style => "height:200px;width:auto;" %><br>
	<%=x.desc%><br><br>
<% end %>
</li>
</center>

app/views/pages/gallery.html.erb
<title>Gallery</title>
<h1>The many faces of Sir Happy</h1>
<ul class="small-block-grid-2">
  <li><%= image_tag "photo3.jpg"%></li>
  <li><%= image_tag "photo2.jpg"%></li>
  <li><%= image_tag "photo4.jpg"%></li>
  <li><%= image_tag "photo1.jpg"%></li>
  <li><%= image_tag "photo5.jpg"%></li>
</ul>

app/views/pages/img.html.erb
<h1>Search Results</h1>
<% if @entries.count > 1 %>
	<p>You have <%= @entries.count %> matches with the image filename <i>"<%= params[:img] %>"</i>:</b><p>
<% elsif @entries.count == 1 %>
	<p>You have <%= @entries.count %> match with the image filename <i>"<%= params[:img] %>"</i>:</b><p>
<% else %>
	<p>Your search returned 0 results. Try another filename!</p>
<% end %>
<center>
<ul class="small-block-grid-2">
<% @entries.each do |x| %>
<li>
	<b><%= x.name%></b><br>
	<%= image_tag x.img, :style => "height:200px;width:auto;" %><br>
	<%=x.desc%><br><br>
<% end %>
</li>
</center>

app/views/pages/index.html.erb
<marquee><h3> Items </h3></marquee>

<center>
<ul class="small-block-grid-2">
<% @items.each do |x| %>
<li>
	<b><%= x.name%></b><br>
	<%= image_tag x.img, :style => "height:200px;width:auto;" %><br>
	<%=x.desc%><br><br>
<% end %>
</li>
</center>

app/views/pages/latest.html.erb
<h3>Latest Item</h3>
<%=@item.created_at.strftime("Created last %A, %B %d, %Y at %I:%M %p")%><br><br>
<center>
<ul class="small-block-grid-1">
<li>
	<b><%= @item.name%></b><br>
	<%= image_tag @item.img, :style => "height:200px;width:auto;" %><br>
	<%=@item.desc%><br>
</li>
</center>

app/views/pages/name.html.erb
<h1>Search Results</h1>
<% if @entries.count > 1 %>
	<p>You have <%= @entries.count %> matches with the name <i>"<%= params[:name] %>"</i>:</b><p>
<% elsif @entries.count == 1 %>
	<p>You have <%= @entries.count %> match with the name <i>"<%= params[:name] %>"</i>:</b><p>
<% else %>
	<p>Your search returned 0 results. Try another name!</p>
<% end %>
<center>
<ul class="small-block-grid-2">
<% @entries.each do |x| %>
<li>
	<b><%= x.name %></b><br>
	<%= image_tag x.img, :style => "height:200px;width:auto;" %><br>
	<%= x.desc %><br><br>
<% end %>
</li>
</center>